In [1]:
# import
import pandas as pd

In [4]:
df = pd.read_csv(r'../Datasets/Airline Dataset.csv')
df.head(5)

,Passenger ID,First Name,Last Name,Gender,Age,Nationality,Airport Name,Airport Country Code,Country Name,Airport Continent,Continents,Departure Date,Arrival Airport,Pilot Name,Flight Status
0,10856,Edithe,Leggis,Female,62,Japan,Coldfoot Airport,US,United States,NAM,North America,6/28/2022,CXF,Edithe Leggis,On Time
1,43872,Elwood,Catt,Male,62,Nicaragua,Kugluktuk Airport,CA,Canada,NAM,North America,12/26/2022,YCO,Elwood Catt,On Time
2,42633,Darby,Felgate,Male,67,Russia,Grenoble-Isère Airport,FR,France,EU,Europe,1/18/2022,GNB,Darby Felgate,On Time
3,78493,Dominica,Pyle,Female,71,China,Ottawa / Gatineau Airport,CA,Canada,NAM,North America,9/16/2022,YND,Dominica Pyle,Delayed
4,82072,Bay,Pencost,Male,21,China,Gillespie Field,US,United States,NAM,North America,2/25/2022,SEE,Bay Pencost,On Time

In [5]:
# first name və last name - i concatenate edərək full name yaradın.
df['First Name'] = df['First Name'] + ' ' + df['Last Name']
print(df)

       Passenger ID         First Name  Last Name  Gender  Age Nationality  \
0             10856      Edithe Leggis     Leggis  Female   62       Japan
1             43872        Elwood Catt       Catt    Male   62   Nicaragua
2             42633      Darby Felgate    Felgate    Male   67      Russia
3             78493      Dominica Pyle       Pyle  Female   71       China
4             82072        Bay Pencost    Pencost    Male   21       China
...             ...                ...        ...     ...  ...         ...
98614         58454     Gareth Mugford    Mugford    Male   85       China
98615         22028     Kasey Benedict   Benedict  Female   19      Russia
98616         61732      Darrin Lucken     Lucken    Male   65   Indonesia
98617         19819    Gayle Lievesley  Lievesley  Female   34       China
98618         14485  Wilhelmine Touret     Touret  Female   10      Poland

                      Airport Name Airport Country Code        Country Name  \
0                 Coldfoot Airport                   US       United States
1                Kugluktuk Airport                   CA              Canada
2           Grenoble-Isère Airport                   FR              France
3        Ottawa / Gatineau Airport                   CA              Canada
4                  Gillespie Field                   US       United States
...                            ...                  ...                 ...
98614               Hasvik Airport                   NO              Norway
98615          Ampampamena Airport                   MG          Madagascar
98616  Albacete-Los Llanos Airport                   ES               Spain
98617               Gagnoa Airport                   CI       Côte d'Ivoire
98618          Yoshkar-Ola Airport                   RU  Russian Federation

      Airport Continent     Continents Departure Date Arrival Airport  \
0                   NAM  North America      6/28/2022             CXF
1                   NAM  North America     12/26/2022             YCO
2                    EU         Europe      1/18/2022             GNB
3                   NAM  North America      9/16/2022             YND
4                   NAM  North America      2/25/2022             SEE
...                 ...            ...            ...             ...
98614                EU         Europe     12/11/2022             HAA
98615                AF         Africa     10/30/2022             IVA
98616                EU         Europe      9/10/2022             ABC
98617                AF         Africa     10/26/2022             GGN
98618                EU         Europe      4/16/2022             JOK

              Pilot Name Flight Status
0          Edithe Leggis       On Time
1            Elwood Catt       On Time
2          Darby Felgate       On Time
3          Dominica Pyle       Delayed
4            Bay Pencost       On Time
...                  ...           ...
98614     Gareth Mugford     Cancelled
98615     Kasey Benedict     Cancelled
98616      Darrin Lucken       On Time
98617    Gayle Lievesley     Cancelled
98618  Wilhelmine Touret       Delayed

[98619 rows x 15 columns]

In [6]:
# Departure Date-i DateTime formatina cevirin
df['Departure Date'] = pd.to_datetime(df['Departure Date'], format = '%m/%d/%Y')
print(df['Departure Date'])

0       2022-06-28
1       2022-12-26
2       2022-01-18
3       2022-09-16
4       2022-02-25
           ...
98614   2022-12-11
98615   2022-10-30
98616   2022-09-10
98617   2022-10-26
98618   2022-04-16
Name: Departure Date, Length: 98619, dtype: datetime64[ns]

In [7]:
# Yaşı 50 və üzəri olan və US- dən səyahət edən bütün recordları tapın
us = df[(df['Age'] >= 50) & (df['Airport Country Code'] == 'US')]
print(us)

       Passenger ID           First Name   Last Name  Gender  Age  \
0             10856        Edithe Leggis      Leggis  Female   62
24            40864        Sayre Stroyan     Stroyan    Male   87
27            37434          Halie Jewar       Jewar  Female   53
41            39880        Zelig Brinded     Brinded    Male   61
45            59791        Haroun holmes      holmes    Male   54
...             ...                  ...         ...     ...  ...
98553         13800         Benoit Epine       Epine    Male   56
98555         13084      Harry Mathewson   Mathewson    Male   54
98556         44743         Maressa Kira        Kira  Female   60
98579         16635  Annabela Billingsly  Billingsly  Female   60
98612         26208          Ody Tineman     Tineman    Male   82

         Nationality                                       Airport Name  \
0              Japan                                   Coldfoot Airport
24         Indonesia                          Elkhart Municipal Airport
27            France            Wiley Post Will Rogers Memorial Airport
41            Brazil  Cincinnati Northern Kentucky International Air...
45     United States                       Susanville Municipal Airport
...              ...                                                ...
98553          China                               Lime Village Airport
98555         Panama          Kerrville Municipal Louis Schreiner Field
98556      Indonesia                        Dodge City Regional Airport
98579         Russia                              Felker Army Air Field
98612      Indonesia                                  Five Mile Airport

      Airport Country Code   Country Name Airport Continent     Continents  \
0                       US  United States               NAM  North America
24                      US  United States               NAM  North America
27                      US  United States               NAM  North America
41                      US  United States               NAM  North America
45                      US  United States               NAM  North America
...                    ...            ...               ...            ...
98553                   US  United States               NAM  North America
98555                   US  United States               NAM  North America
98556                   US  United States               NAM  North America
98579                   US  United States               NAM  North America
98612                   US  United States               NAM  North America

      Departure Date Arrival Airport           Pilot Name Flight Status
0         2022-06-28             CXF        Edithe Leggis       On Time
24        2022-03-20             EKI        Sayre Stroyan     Cancelled
27        2022-12-05             BRW          Halie Jewar       Delayed
41        2022-06-16             CVG        Zelig Brinded       On Time
45        2022-03-21             SVE        Haroun holmes       On Time
...              ...             ...                  ...           ...
98553     2022-09-05             LVD         Benoit Epine     Cancelled
98555     2022-04-11             ERV      Harry Mathewson       Delayed
98556     2022-05-09             DDC         Maressa Kira     Cancelled
98579     2022-03-05             FAF  Annabela Billingsly       On Time
98612     2022-03-17             FMC          Ody Tineman       Delayed

[10077 rows x 15 columns]

In [8]:
# Yaşa görə desc order ilə sıralayın
sorted= us.sort_values(by='Age', ascending=False)
print(sorted)

       Passenger ID          First Name   Last Name  Gender  Age  \
22194         47768        Teddie Fooks       Fooks    Male   90
27105         52263     Camey Wallentin   Wallentin    Male   90
76394         82595         Ogden Sturr       Sturr    Male   90
3161          31275       Jodi Colchett    Colchett    Male   90
52095         52589        Borg Burress     Burress    Male   90
...             ...                 ...         ...     ...  ...
35948         54822         Kylen Clamo       Clamo  Female   50
79358         51398          Pauli Pert        Pert  Female   50
36173         50683  Bartlett Gutierrez   Gutierrez    Male   50
70382         50505       Reese Bordman     Bordman    Male   50
55226         79011  Beatrix McCullough  McCullough  Female   50

         Nationality                          Airport Name  \
22194  United States         Stewart International Airport
27105       Portugal              Fairchild Air Force Base
76394          China             University Oxford Airport
3161           China                  Jack Edwards Airport
52095         Russia     Louisville Winston County Airport
...              ...                                   ...
35948      Indonesia               Tioga Municipal Airport
79358      Indonesia                       Tonopah Airport
36173         Poland  Theodore Francis Green State Airport
70382          China             Flagstaff Pulliam Airport
55226      Argentina                Maxwell Air Force Base

      Airport Country Code   Country Name Airport Continent     Continents  \
22194                   US  United States               NAM  North America
27105                   US  United States               NAM  North America
76394                   US  United States               NAM  North America
3161                    US  United States               NAM  North America
52095                   US  United States               NAM  North America
...                    ...            ...               ...            ...
35948                   US  United States               NAM  North America
79358                   US  United States               NAM  North America
36173                   US  United States               NAM  North America
70382                   US  United States               NAM  North America
55226                   US  United States               NAM  North America

      Departure Date Arrival Airport          Pilot Name Flight Status
22194     2022-01-22             SWF        Teddie Fooks     Cancelled
27105     2022-01-27             SKA     Camey Wallentin       Delayed
76394     2022-02-03             UOX         Ogden Sturr       Delayed
3161      2022-05-23             GUF       Jodi Colchett     Cancelled
52095     2022-03-19             LMS        Borg Burress       Delayed
...              ...             ...                 ...           ...
35948     2022-11-18             VEX         Kylen Clamo       On Time
79358     2022-10-21             TPH          Pauli Pert       On Time
36173     2022-10-24             PVD  Bartlett Gutierrez       Delayed
70382     2022-05-07             FLG       Reese Bordman       On Time
55226     2022-06-05             MXF  Beatrix McCullough     Cancelled

[10077 rows x 15 columns]

In [9]:
# Flight statusa görə qruplaşdırın və hər statusa görə ortalama sərnişin yaşının ortalamasını tapıns
average = df.groupby('Flight Status')['Age'].mean()
print(average)

Flight Status
Cancelled    45.464392
Delayed      45.583595
On Time      45.464227
Name: Age, dtype: float64

In [10]:
# Create a new column 'Age Group' to categorize passengers into 'Youth' (age < 30), 'Adult' (30 ≤ age < 60), and 'Senior' (age ≥ 60).
# Age Group deyə yeni kateqorik sütun yaradın. Youth 30 dan azdırsa Adult 30 a bərabər və ya 60 dan azdırsa Adult , 60 a bərabər və 60 dan yuxarıdırsa Senior olaraq status versin.


def age_group(age):
    if age < 30:
        return 'Youth'
    elif 30 <= age < 60:
        return 'Adult'
    else:
        return 'Senior'

df['Age Group'] = df['Age'].apply(age_group)

print(df)

       Passenger ID         First Name  Last Name  Gender  Age Nationality  \
0             10856      Edithe Leggis     Leggis  Female   62       Japan
1             43872        Elwood Catt       Catt    Male   62   Nicaragua
2             42633      Darby Felgate    Felgate    Male   67      Russia
3             78493      Dominica Pyle       Pyle  Female   71       China
4             82072        Bay Pencost    Pencost    Male   21       China
...             ...                ...        ...     ...  ...         ...
98614         58454     Gareth Mugford    Mugford    Male   85       China
98615         22028     Kasey Benedict   Benedict  Female   19      Russia
98616         61732      Darrin Lucken     Lucken    Male   65   Indonesia
98617         19819    Gayle Lievesley  Lievesley  Female   34       China
98618         14485  Wilhelmine Touret     Touret  Female   10      Poland

                      Airport Name Airport Country Code        Country Name  \
0                 Coldfoot Airport                   US       United States
1                Kugluktuk Airport                   CA              Canada
2           Grenoble-Isère Airport                   FR              France
3        Ottawa / Gatineau Airport                   CA              Canada
4                  Gillespie Field                   US       United States
...                            ...                  ...                 ...
98614               Hasvik Airport                   NO              Norway
98615          Ampampamena Airport                   MG          Madagascar
98616  Albacete-Los Llanos Airport                   ES               Spain
98617               Gagnoa Airport                   CI       Côte d'Ivoire
98618          Yoshkar-Ola Airport                   RU  Russian Federation

      Airport Continent     Continents Departure Date Arrival Airport  \
0                   NAM  North America     2022-06-28             CXF
1                   NAM  North America     2022-12-26             YCO
2                    EU         Europe     2022-01-18             GNB
3                   NAM  North America     2022-09-16             YND
4                   NAM  North America     2022-02-25             SEE
...                 ...            ...            ...             ...
98614                EU         Europe     2022-12-11             HAA
98615                AF         Africa     2022-10-30             IVA
98616                EU         Europe     2022-09-10             ABC
98617                AF         Africa     2022-10-26             GGN
98618                EU         Europe     2022-04-16             JOK

              Pilot Name Flight Status Age Group
0          Edithe Leggis       On Time    Senior
1            Elwood Catt       On Time    Senior
2          Darby Felgate       On Time    Senior
3          Dominica Pyle       Delayed    Senior
4            Bay Pencost       On Time     Youth
...                  ...           ...       ...
98614     Gareth Mugford     Cancelled    Senior
98615     Kasey Benedict     Cancelled     Youth
98616      Darrin Lucken       On Time    Senior
98617    Gayle Lievesley     Cancelled     Adult
98618  Wilhelmine Touret       Delayed     Youth

[98619 rows x 16 columns]

In [11]:
# ən çox departure olan 3 ölkəni tapın
top_countries = df['Country Name'].value_counts().head(3)
print(top_countries)

Country Name
United States    22104
Australia         6370
Canada            5424
Name: count, dtype: int64

In [12]:
# Senior sərnişinlərin ən çox getdiyi destination- ları tapın
senior_destinations = df[df['Age Group'] == 'Senior']['Arrival Airport'].value_counts().head()
print(senior_destinations)

Arrival Airport
0      280
PCO     14
AHT     13
WMP     13
BDE     13
Name: count, dtype: int64

In [13]:
# Delay statusunda olan gedişlərin faizini totala nisbətən tapın.
delayed_percentage = (df['Flight Status'] == 'Delayed').mean() * 100
print(delayed_percentage)

33.29074519108894